# Generated by Django 4.1.6 on 2023-05-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luggage_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='luggage',
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(default='Poland', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CustomerLuggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.customer')),
                ('luggage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.luggage')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='luggages',
            field=models.ManyToManyField(through='airline.CustomerLuggage', to='airline.luggage'),
        ),
    ]
