# Generated by Django 4.1.6 on 2023-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_alter_airport_id_alter_booking_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
